use gba::video::Tile4;

pub struct Sprite {
    tiles: &'static [ Tile4 ],
    palette_bank: u8
}

// Insert all of the code generated by the build sript.
// This will contain static definitions for all of our aseprite files.
include!(concat!(env!("OUT_DIR"), "/sprite_data.rs"));
